#!/bin/bash

# Simple hex game arbiter
if test -z "$3"
then
echo "Usage: $0 <player1> <player2> <logfile> [iter1] [iter2]"
echo "Example: $0 ./player1 ./player2 log.txt 1000 1000"
exit
fi

iter1=$4
iter2=$5

if test -z "$4"
then
iter1=1000
fi

if test -z "$5"
then
iter2=1000
fi

exec 3>> $3

echo "Match $1 X@$iter1 vs $2 O@$iter2 on $(date)" >&3

declare -a p1
coproc p1 {
    exec $2 O 11 $iter2 | tee -a >(cat - >&3)
}

$1 X 11 $iter1 <&${p1[0]} > >(tee -a >(cat - >&3) >&${p1[1]})

# wait for the coprocess to finish too.
wait $p1_PID

echo "Ended on $(date)" >&3
echo "" >&3
